[package]
name = "trilion_poker_server"
version = "0.1.0"
authors = ["Yuhanun Citgez <yuhanun.c@mendel.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.115"
serde_json = "1.0.57"